Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  LatestAmiId:
    Description: (DO NOT CHANGE)
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'
    AllowedValues:
      - /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

Resources:
  SingaporeVPC:
    Type: AWS::EC2::VPC
    Properties:
     CidrBlock: 10.2.0.0/16
     Tags:
        - Key: Name
          Value: Singapore-VPC

  SingaporeIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Singapore-IGW

  SingaporeIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref SingaporeIGW
      VpcId: !Ref SingaporeVPC

  SingaporePublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SingaporeVPC
      Tags:
        - Key: Name
          Value: Singapore-Public-RT

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: SingaporeIGWAttachment
    Properties:
      RouteTableId: !Ref SingaporePublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref SingaporeIGW

  SingaporePublicSN:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SingaporeVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.2.1.0/24
      Tags:
        - Key: Name
          Value: Singapore-Public-SN

  SingaporePublicSNRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SingaporePublicRT
      SubnetId: !Ref SingaporePublicSN

  SingaporeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access via port 22
      VpcId: !Ref SingaporeVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0

  SingaporePublicEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: Singapore-Public-EC2
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SingaporePublicSN
          GroupSet:
          - !Ref SingaporeSecurityGroup
          PrivateIpAddress: 10.2.1.10
          AssociatePublicIpAddress: true
      UserData:
        Fn::Base64: |
          #!/bin/bash
          hostnamectl --static set-hostname Singapore-EC2
          cat <<EOT >> /etc/profile.d/prompt.sh
          export PS1="[\[\e[1;31m\]\u\[\e[m\]@\[\e[1;32m\]\h\[\e[m\]: \[\e[1;36m\]\w\[\e[m\]]#"
          EOT
          source /etc/profile
          
########### TGW 연결 서브넷 생성 ########################
 
  SingaporeVPCRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SingaporeVPC
      Tags:
        - Key: Name
          Value: TGW-SingaporeVPC-TGWAttachRT

  SingaporeVPCSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SingaporeVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.2.2.0/24
      Tags:
        - Key: Name
          Value: TGW-SingaporeVPC-Subnet2
          
  SingaporeVPCSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref SingaporeVPCRouteTable2
      SubnetId: !Ref SingaporeVPCSubnet2
      
############# TGW 생성 ############
      
  TransitGateway1:
    Type: AWS::EC2::TransitGateway
    Properties:
      Tags:
        - Key: Name
          Value: TGW1

  TransitGatewayAtt1:
    Type: AWS::EC2::TransitGatewayAttachment
    DependsOn: SingaporeVPC
    Properties:
      VpcId: !Ref SingaporeVPC
      SubnetIds:
      - !Ref SingaporeVPCSubnet2
      TransitGatewayId: !Ref TransitGateway1
      Tags:
        - Key: Name
          Value: TGW1-ATT1-SingaporeVPC
       
  SeoulRoute3:
    Type: AWS::EC2::Route
    DependsOn: TransitGatewayAtt1
    Properties:
      RouteTableId: !Ref SingaporePublicRT
      DestinationCidrBlock: 10.1.0.0/16
      TransitGatewayId: !Ref TransitGateway1
      
  TGWStacticRoute:
    Type: AWS::EC2::TransitGatewayRoute
    Properties:
      DestinationCidrBlock: 10.1.0.0/16
      TransitGatewayRouteTableId: tgw-rtb-09d5ec8b0ba6d562a
      TransitGatewayAttachmentId: tgw-attach-0b6f146f0e32d4ffe

Outputs:
  SingaporeTransitGatewayID:
    Description: Singapore TransitGateway ID
    Value: !Ref TransitGateway1

