Parameters:

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  LatestAmiTd:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:

# =========================
# VPC
# =========================
  SAOPAULOVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: SAOPAULOVPC








# =========================
# Internet Gateway
# =========================
  SAOPAULO1GW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: SAOPAULO1GW

  AttachGateway1:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SAOPAULOVPC
      InternetGatewayId: !Ref SAOPAULO1GW




# =========================
# Subnets
# =========================
  SAOPAULOPublicSN1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SAOPAULOVPC
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: SAOPAULOPublicSN1

  SAOPAULOPublicSN2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SAOPAULOVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [2, !GetAZs '']
      Tags:
        - Key: Name
          Value: SAOPAULOPublicSN2





# =========================
# Route Tables
# =========================
  SAOPAULOPublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref SAOPAULOVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway1
    Properties:
      RouteTableId: !Ref SAOPAULOPublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref SAOPAULO1GW

  PublicSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SAOPAULOPublicSN1
      RouteTableId: !Ref SAOPAULOPublicRT

  PublicSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SAOPAULOPublicSN2
      RouteTableId: !Ref SAOPAULOPublicRT





# =========================
# Security Groups
# =========================




  WEBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web SG
      VpcId: !Ref SAOPAULOVPC
      SecurityGroupIngress:

        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          # SourceSecurityGroupId: !Ref ALBSecurityGroup
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: icmp #ping용
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0





# ec2
  
  SAOPAULOEC21:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref LatestAmiTd
      KeyName: !Ref KeyName
      SubnetId: !Ref SAOPAULOPublicSN1
      SecurityGroupIds:
        - !Ref WEBSG
      Tags:
        - Key: Name
          Value: SAOPAULOEC21
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            TOKEN=$(curl -sS -X PUT "http://169.254.169.254/latest/api/token" \
              -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
            RZAZ=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/availability-zone-id)
            IID=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)
            LIP=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/local-ipv4)              
            wget https://cloudneta.github.io/test.jpg
            wget -P /usr/share/nginx/html/ https://cloudneta.github.io/test.jpg
            dnf install -y nginx
            echo "<head><link rel='icon' href='data:;base64,iVBORw0KGgo='></head><h1>RegionAz($RZAZ) : Instance ID($IID) : Private IP($LIP) : Main SAOPAULO WEB PAGE1111111111111</h1><img src='test.jpg'>" > /usr/share/nginx/html/index.html
            systemctl start nginx
            systemctl enable nginx

  SAOPAULOEC22:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref LatestAmiTd
      KeyName: !Ref KeyName
      SubnetId: !Ref SAOPAULOPublicSN2
      SecurityGroupIds:
        - !Ref WEBSG
      Tags:
        - Key: Name
          Value: SAOPAULOEC22
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            TOKEN=$(curl -sS -X PUT "http://169.254.169.254/latest/api/token" \
              -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
            RZAZ=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/availability-zone-id)
            IID=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)
            LIP=$(curl -sS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/local-ipv4)              
            wget https://cloudneta.github.io/test.jpg
            wget -P /usr/share/nginx/html/ https://cloudneta.github.io/test.jpg
            dnf install -y nginx
            echo "<head><link rel='icon' href='data:;base64,iVBORw0KGgo='></head><h1>RegionAz($RZAZ) : Instance ID($IID) : Private IP($LIP) : SAOPAULO WEB PAGE222222222222222</h1><img src='test.jpg'>" > /usr/share/nginx/html/index.html
            systemctl start nginx
            systemctl enable nginx





      
